kind: pipeline
name: default

steps:
  - name: deps download
    image: microlayers/golang-with-extras:1.11.4-alpine3.8
    volumes:
      - name: gocache
        path: /gocache
    environment:
      GOPATH: /go/
    commands:
      - ln -s /gocache /go/             # link the go's cache volume to GOPATH
      - mkdir -p /go/src
      - mkdir -p /go/pkg
      - ln -s /drone/src /go/src/ns-auth
      - GO111MODULE=on go mod download  # download the mod dependencies
      - cd /go/src/ns-auth
      - GO111MODULE=off go get -t ./... # download the dependencies (for gometalinter)
  - name: linting
    image: microlayers/golang-with-extras:1.11.4-alpine3.8
    volumes:
      - name: gocache
        path: /gocache
    environment:
      GOPATH: /go/
    commands:
      - ln -s /gocache /go/                 # link the go's cache volume to GOPATH
      - ln -s /drone/src /go/src/ns-auth    # hack to let gometalinter work (thinking it's not a module)
      - gometalinter ./...                  # run gometalinter

volumes:
  - name: gocache
    temp: {}
