version: "3.7"

services:
  postgres:
    image: postgres:11.1-alpine
    env_file: postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.4.0-bionic
    env_file: mariadb.env
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:5.0.2-alpine3.8
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:4.0.4-xenial
    volumes:
      - mongo_db:/data/db
      - mongo_configdb:/data/configdb

volumes:
  postgres_data:
  mariadb_data:
  redis_data:
  mongo_db:
  mongo_configdb:
