// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"ns-auth/configuration"
	"ns-auth/storage"
)

// Injectors from wire.go:

func GetUsernamePasswordAuthentication(config *configuration.Configuration) *UsernamePasswordAuthentication {
	hasher := _injectorHasher(config)
	storage := _injectorStorage(config, hasher)
	usernamePasswordAuthentication := NewUsernamePasswordAuthentication(storage, hasher)
	return usernamePasswordAuthentication
}

// wire.go:

func _injectorStorage(
	config *configuration.Configuration,
	hasher storage.Hasher,
) *storage.Storage {
	switch config.Authentication.Store.Type {
	case "memory":
	default:
		return NewMemoryStorage(hasher)
	}

	return NewMemoryStorage(hasher)
}

func _injectorHasher(config *configuration.Configuration) storage.Hasher {
	salt := HasherSalt(config.Authentication.Hasher.Salt)

	switch config.Authentication.Hasher.Type {
	case "standard":
	default:
		return NewStdHasher(salt)
	}

	return NewStdHasher(salt)
}
