// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/AuthenticationResponse.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticationResponse struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpiryDate           int64    `protobuf:"varint,3,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResponse) Reset()         { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()    {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_AuthenticationResponse_36198eceaa307aaa, []int{0}
}
func (m *AuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResponse.Unmarshal(m, b)
}
func (m *AuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResponse.Merge(dst, src)
}
func (m *AuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResponse.Size(m)
}
func (m *AuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResponse proto.InternalMessageInfo

func (m *AuthenticationResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *AuthenticationResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AuthenticationResponse) GetExpiryDate() int64 {
	if m != nil {
		return m.ExpiryDate
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthenticationResponse)(nil), "messages.AuthenticationResponse")
}

func init() {
	proto.RegisterFile("messages/AuthenticationResponse.proto", fileDescriptor_AuthenticationResponse_36198eceaa307aaa)
}

var fileDescriptor_AuthenticationResponse_36198eceaa307aaa = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x77, 0x2c, 0x2d, 0xc9, 0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x4e, 0x2c,
	0xc9, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x80, 0x29, 0x53, 0xaa, 0xe2, 0x12, 0xc3, 0xae, 0x52, 0x48, 0x86, 0x8b, 0x33,
	0xb1, 0xb4, 0x24, 0x23, 0x24, 0x3f, 0x3b, 0x35, 0x4f, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0x21, 0x20, 0xa4, 0xc4, 0xc5, 0x53, 0x94, 0x9a, 0x56, 0x94, 0x5a, 0x0c, 0x55, 0xc0, 0x04, 0x56,
	0x80, 0x22, 0x26, 0x24, 0xc7, 0xc5, 0x95, 0x5a, 0x51, 0x90, 0x59, 0x54, 0xe9, 0x92, 0x58, 0x92,
	0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x24, 0x92, 0xc4, 0x06, 0x76, 0x8c, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x4e, 0x12, 0x12, 0xa5, 0xb5, 0x00, 0x00, 0x00,
}
