// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/ResponseWrapper.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseWrapper struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorCode            uint32   `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseWrapper) Reset()         { *m = ResponseWrapper{} }
func (m *ResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ResponseWrapper) ProtoMessage()    {}
func (*ResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ResponseWrapper_aca4f5e6ae7c455a, []int{0}
}
func (m *ResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWrapper.Unmarshal(m, b)
}
func (m *ResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWrapper.Marshal(b, m, deterministic)
}
func (dst *ResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWrapper.Merge(dst, src)
}
func (m *ResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ResponseWrapper.Size(m)
}
func (m *ResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWrapper proto.InternalMessageInfo

func (m *ResponseWrapper) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ResponseWrapper) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ResponseWrapper) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ResponseWrapper) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseWrapper)(nil), "messages.ResponseWrapper")
}

func init() {
	proto.RegisterFile("messages/ResponseWrapper.proto", fileDescriptor_ResponseWrapper_aca4f5e6ae7c455a)
}

var fileDescriptor_ResponseWrapper_aca4f5e6ae7c455a = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x0f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x0d, 0x2f, 0x4a,
	0x2c, 0x28, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xc9, 0x2b, 0xd5,
	0x72, 0xf1, 0xa3, 0x29, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0xcf, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x08, 0x62, 0xca, 0xcf, 0x16, 0x92, 0xe1, 0xe2, 0x4c, 0x2d, 0x2a, 0xca, 0x2f, 0x72, 0xce, 0x4f,
	0x49, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0d, 0x42, 0x08, 0x08, 0x29, 0x71, 0xf1, 0x80, 0x39,
	0xbe, 0x10, 0x13, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0x50, 0xc4, 0x84, 0x24, 0xb8, 0xd8,
	0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x24, 0x58, 0x14, 0x18, 0x35, 0x78, 0x82, 0x60, 0xdc,
	0x24, 0x36, 0xb0, 0x7b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xfe, 0x85, 0x0d, 0xb1,
	0x00, 0x00, 0x00,
}
