// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/Token.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenDiscoverRequestPayload struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenDiscoverRequestPayload) Reset()         { *m = TokenDiscoverRequestPayload{} }
func (m *TokenDiscoverRequestPayload) String() string { return proto.CompactTextString(m) }
func (*TokenDiscoverRequestPayload) ProtoMessage()    {}
func (*TokenDiscoverRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_Token_c743765ac0a52eae, []int{0}
}
func (m *TokenDiscoverRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDiscoverRequestPayload.Unmarshal(m, b)
}
func (m *TokenDiscoverRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDiscoverRequestPayload.Marshal(b, m, deterministic)
}
func (dst *TokenDiscoverRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDiscoverRequestPayload.Merge(dst, src)
}
func (m *TokenDiscoverRequestPayload) XXX_Size() int {
	return xxx_messageInfo_TokenDiscoverRequestPayload.Size(m)
}
func (m *TokenDiscoverRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDiscoverRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDiscoverRequestPayload proto.InternalMessageInfo

func (m *TokenDiscoverRequestPayload) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenDiscoverRequestPayload) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type TokenDiscoverResponsePayload struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenDiscoverResponsePayload) Reset()         { *m = TokenDiscoverResponsePayload{} }
func (m *TokenDiscoverResponsePayload) String() string { return proto.CompactTextString(m) }
func (*TokenDiscoverResponsePayload) ProtoMessage()    {}
func (*TokenDiscoverResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_Token_c743765ac0a52eae, []int{1}
}
func (m *TokenDiscoverResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDiscoverResponsePayload.Unmarshal(m, b)
}
func (m *TokenDiscoverResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDiscoverResponsePayload.Marshal(b, m, deterministic)
}
func (dst *TokenDiscoverResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDiscoverResponsePayload.Merge(dst, src)
}
func (m *TokenDiscoverResponsePayload) XXX_Size() int {
	return xxx_messageInfo_TokenDiscoverResponsePayload.Size(m)
}
func (m *TokenDiscoverResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDiscoverResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDiscoverResponsePayload proto.InternalMessageInfo

func (m *TokenDiscoverResponsePayload) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TokenDiscoverResponsePayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenDiscoverResponsePayload) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenDiscoverRequestPayload)(nil), "messages.TokenDiscoverRequestPayload")
	proto.RegisterType((*TokenDiscoverResponsePayload)(nil), "messages.TokenDiscoverResponsePayload")
}

func init() { proto.RegisterFile("messages/Token.proto", fileDescriptor_Token_c743765ac0a52eae) }

var fileDescriptor_Token_c743765ac0a52eae = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x0f, 0xc9, 0xcf, 0x4e, 0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x80, 0x89, 0x2a, 0x79, 0x73, 0x49, 0x83, 0x25, 0x5c, 0x32, 0x8b, 0x93, 0xf3, 0xcb,
	0x52, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x02, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53,
	0x84, 0x44, 0xb8, 0x58, 0x4b, 0x40, 0xd2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e,
	0x90, 0x18, 0x17, 0x5b, 0x4a, 0x7e, 0x6e, 0x62, 0x66, 0x9e, 0x04, 0x13, 0x58, 0x18, 0xca, 0x53,
	0xca, 0xe2, 0x92, 0x41, 0x33, 0xac, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x66, 0x9a, 0x18, 0x17,
	0x5b, 0x69, 0x71, 0x6a, 0x91, 0xa7, 0x0b, 0xd4, 0x38, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0x03, 0xc4,
	0xca, 0x4b, 0xcc, 0x4d, 0x85, 0x9a, 0x08, 0xe7, 0x23, 0xd9, 0xc5, 0x8c, 0x6c, 0x57, 0x12, 0x1b,
	0xd8, 0x27, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xe1, 0xb4, 0x30, 0xe1, 0x00, 0x00,
	0x00,
}
