// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/UsernamePasswordRequestPayload.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UsernamePasswordRequestPayload struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernamePasswordRequestPayload) Reset()         { *m = UsernamePasswordRequestPayload{} }
func (m *UsernamePasswordRequestPayload) String() string { return proto.CompactTextString(m) }
func (*UsernamePasswordRequestPayload) ProtoMessage()    {}
func (*UsernamePasswordRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_UsernamePasswordRequestPayload_d3edc068f59de57c, []int{0}
}
func (m *UsernamePasswordRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernamePasswordRequestPayload.Unmarshal(m, b)
}
func (m *UsernamePasswordRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernamePasswordRequestPayload.Marshal(b, m, deterministic)
}
func (dst *UsernamePasswordRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernamePasswordRequestPayload.Merge(dst, src)
}
func (m *UsernamePasswordRequestPayload) XXX_Size() int {
	return xxx_messageInfo_UsernamePasswordRequestPayload.Size(m)
}
func (m *UsernamePasswordRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernamePasswordRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UsernamePasswordRequestPayload proto.InternalMessageInfo

func (m *UsernamePasswordRequestPayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsernamePasswordRequestPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UsernamePasswordRequestPayload) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func init() {
	proto.RegisterType((*UsernamePasswordRequestPayload)(nil), "messages.UsernamePasswordRequestPayload")
}

func init() {
	proto.RegisterFile("messages/UsernamePasswordRequestPayload.proto", fileDescriptor_UsernamePasswordRequestPayload_d3edc068f59de57c)
}

var fileDescriptor_UsernamePasswordRequestPayload_d3edc068f59de57c = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x0f, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x0d, 0x48, 0x2c,
	0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x48, 0xac, 0xcc,
	0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x29, 0x57, 0x2a, 0xe0,
	0x92, 0xc3, 0xaf, 0x43, 0x48, 0x8a, 0x8b, 0xa3, 0x14, 0xaa, 0x42, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0xce, 0x07, 0xc9, 0x15, 0x40, 0x75, 0x49, 0x30, 0x41, 0xe4, 0x60, 0x7c, 0x21, 0x31,
	0x2e, 0xb6, 0x94, 0xfc, 0xdc, 0xc4, 0xcc, 0x3c, 0x09, 0x66, 0xb0, 0x0c, 0x94, 0x97, 0xc4, 0x06,
	0x76, 0x82, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x43, 0x84, 0xce, 0x3b, 0xb3, 0x00, 0x00, 0x00,
}
