// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/UserCreationResponse.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserCreationResponsePayload struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreationResponsePayload) Reset()         { *m = UserCreationResponsePayload{} }
func (m *UserCreationResponsePayload) String() string { return proto.CompactTextString(m) }
func (*UserCreationResponsePayload) ProtoMessage()    {}
func (*UserCreationResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_UserCreationResponse_37051a51db2ef558, []int{0}
}
func (m *UserCreationResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreationResponsePayload.Unmarshal(m, b)
}
func (m *UserCreationResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreationResponsePayload.Marshal(b, m, deterministic)
}
func (dst *UserCreationResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreationResponsePayload.Merge(dst, src)
}
func (m *UserCreationResponsePayload) XXX_Size() int {
	return xxx_messageInfo_UserCreationResponsePayload.Size(m)
}
func (m *UserCreationResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreationResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreationResponsePayload proto.InternalMessageInfo

func (m *UserCreationResponsePayload) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCreationResponsePayload)(nil), "messages.UserCreationResponsePayload")
}

func init() {
	proto.RegisterFile("messages/UserCreationResponse.proto", fileDescriptor_UserCreationResponse_37051a51db2ef558)
}

var fileDescriptor_UserCreationResponse_37051a51db2ef558 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xce, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x0f, 0x2d, 0x4e, 0x2d, 0x72, 0x2e, 0x4a, 0x4d, 0x2c, 0xc9, 0xcc,
	0xcf, 0x0b, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x80, 0x29, 0x52, 0xd2, 0xe5, 0x92, 0xc6, 0xa6, 0x2e, 0x20, 0xb1, 0x32, 0x27, 0x3f, 0x31,
	0x45, 0x88, 0x8f, 0x8b, 0xc9, 0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0xc9, 0xd3,
	0x25, 0x89, 0x0d, 0xac, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x72, 0x90, 0x3a, 0x66,
	0x00, 0x00, 0x00,
}
