// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/UsernamePassword.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UsernamePasswordLoginRequestPayload struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernamePasswordLoginRequestPayload) Reset()         { *m = UsernamePasswordLoginRequestPayload{} }
func (m *UsernamePasswordLoginRequestPayload) String() string { return proto.CompactTextString(m) }
func (*UsernamePasswordLoginRequestPayload) ProtoMessage()    {}
func (*UsernamePasswordLoginRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_UsernamePassword_6004971300e8753a, []int{0}
}
func (m *UsernamePasswordLoginRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernamePasswordLoginRequestPayload.Unmarshal(m, b)
}
func (m *UsernamePasswordLoginRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernamePasswordLoginRequestPayload.Marshal(b, m, deterministic)
}
func (dst *UsernamePasswordLoginRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernamePasswordLoginRequestPayload.Merge(dst, src)
}
func (m *UsernamePasswordLoginRequestPayload) XXX_Size() int {
	return xxx_messageInfo_UsernamePasswordLoginRequestPayload.Size(m)
}
func (m *UsernamePasswordLoginRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernamePasswordLoginRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UsernamePasswordLoginRequestPayload proto.InternalMessageInfo

func (m *UsernamePasswordLoginRequestPayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsernamePasswordLoginRequestPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UsernamePasswordLoginRequestPayload) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type UsernamePasswordAddUserRequestPayload struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernamePasswordAddUserRequestPayload) Reset()         { *m = UsernamePasswordAddUserRequestPayload{} }
func (m *UsernamePasswordAddUserRequestPayload) String() string { return proto.CompactTextString(m) }
func (*UsernamePasswordAddUserRequestPayload) ProtoMessage()    {}
func (*UsernamePasswordAddUserRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_UsernamePassword_6004971300e8753a, []int{1}
}
func (m *UsernamePasswordAddUserRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernamePasswordAddUserRequestPayload.Unmarshal(m, b)
}
func (m *UsernamePasswordAddUserRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernamePasswordAddUserRequestPayload.Marshal(b, m, deterministic)
}
func (dst *UsernamePasswordAddUserRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernamePasswordAddUserRequestPayload.Merge(dst, src)
}
func (m *UsernamePasswordAddUserRequestPayload) XXX_Size() int {
	return xxx_messageInfo_UsernamePasswordAddUserRequestPayload.Size(m)
}
func (m *UsernamePasswordAddUserRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernamePasswordAddUserRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UsernamePasswordAddUserRequestPayload proto.InternalMessageInfo

func (m *UsernamePasswordAddUserRequestPayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsernamePasswordAddUserRequestPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UsernamePasswordAddUserRequestPayload) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func init() {
	proto.RegisterType((*UsernamePasswordLoginRequestPayload)(nil), "messages.UsernamePasswordLoginRequestPayload")
	proto.RegisterType((*UsernamePasswordAddUserRequestPayload)(nil), "messages.UsernamePasswordAddUserRequestPayload")
}

func init() {
	proto.RegisterFile("messages/UsernamePassword.proto", fileDescriptor_UsernamePassword_6004971300e8753a)
}

var fileDescriptor_UsernamePassword_6004971300e8753a = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x0f, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x0d, 0x48, 0x2c,
	0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x29, 0x50,
	0x2a, 0xe5, 0x52, 0x46, 0x57, 0xe3, 0x93, 0x9f, 0x9e, 0x99, 0x17, 0x94, 0x5a, 0x58, 0x9a, 0x5a,
	0x5c, 0x12, 0x90, 0x58, 0x99, 0x93, 0x9f, 0x98, 0x22, 0x24, 0xc5, 0xc5, 0x51, 0x0a, 0x55, 0x26,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x83, 0xe4, 0x0a, 0xa0, 0x5a, 0x25, 0x98, 0x20,
	0x72, 0x30, 0xbe, 0x90, 0x18, 0x17, 0x5b, 0x4a, 0x7e, 0x6e, 0x62, 0x66, 0x9e, 0x04, 0x33, 0x58,
	0x06, 0xca, 0x53, 0x2a, 0xe7, 0x52, 0x45, 0xb7, 0xd6, 0x31, 0x25, 0x05, 0x24, 0x44, 0x5b, 0x8b,
	0x93, 0xd8, 0xc0, 0x01, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x5c, 0x3b, 0xd2, 0x23,
	0x01, 0x00, 0x00,
}
