// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"ns-auth/configuration"
	"ns-auth/service"
)

// Injectors from wire.go:

func GetProtoHandler(config *configuration.Configuration) *ProtoHandler {
	usernamePasswordAuthentication := service.GetUsernamePasswordAuthentication(config)
	usernamePasswordProtoHandler := NewUsernamePasswordProtoHandler(usernamePasswordAuthentication)
	protoHandler := NewProtoHandler(usernamePasswordProtoHandler)
	return protoHandler
}
