// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"ns-auth/configuration"
)

// Injectors from wire.go:

func GetProtoHandler(config *configuration.Configuration) *ProtoHandler {
	usernamePasswordProtoHandler := NewUsernamePasswordProtoHandler()
	protoHandler := NewProtoHandler(usernamePasswordProtoHandler)
	return protoHandler
}
