// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"ns-auth/configuration"
	"ns-auth/service"
	"ns-auth/storage"
)

// Injectors from wire.go:

func GetProtoHandler(config *configuration.Configuration) *ProtoHandler {
	usernamePasswordAuthentication := service.GetUsernamePasswordAuthentication(config)
	usernamePasswordProtoHandler := NewUsernamePasswordProtoHandler(usernamePasswordAuthentication)
	hasher := service.GetHasher(config)
	storage := service.GetStorage(config, hasher)
	tokenStorage := _tokenStorageInjector(storage)
	tokenProtoHandler := NewTokenProtoHandler(tokenStorage)
	protoHandler := NewProtoHandler(usernamePasswordProtoHandler, tokenProtoHandler)
	return protoHandler
}

// wire.go:

func _tokenStorageInjector(storage2 *storage.Storage,
) storage.TokenStorage {
	return storage2.Token
}
